### ISSUE TITLE
Shape not aligned

### ISSUE THREAD

**Issue by TTLL0928** [xxradon/ONNXToCaffe#11]
Traceback (most recent call last):
  File "convertCaffe.py", line 123, in <module>
    compareOnnxAndCaffe(onnx_path,prototxt_path,caffemodel_path)
  File "/home/dldev/ONNXToCaffe/modelComparator.py", line 141, in compareOnnxAndCaffe
    check_results(net_results, onnx_info, caffe_info)
  File "/home/dldev/ONNXToCaffe/modelComparator.py", line 95, in check_results
    dot_result = np.dot(result.flatten(), caffe_results[i].flatten())
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (4096000,) and (4029045,) not aligned: 4096000 (dim 0) != 4029045 (dim 0)

**Comment by TTLL0928** [comment]
似乎有convTranspose就会出问题
