### ISSUE TITLE
AttributeError: upsample_param

### ISSUE THREAD

**Issue by HuHu246** [xxradon/ONNXToCaffe#12]
博主您好，我在转换Mobilenet+fpn时都遇到了这样的错误
Traceback (most recent call last):
  File "convertCaffe.py", line 122, in <module>
    convertToCaffe(graph, opset_version, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 79, in convertToCaffe
    layers[id] = layer._to_proto()
  File "/home/dongly/ONNXToCaffe-master/MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "/home/dongly/ONNXToCaffe-master/MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: upsample_param
请求博主指导，非常感谢。

**Comment by Lacacy** [comment]
你解决掉这个问题了吗？？？
