### ISSUE TITLE
can torch.split be support

### ISSUE THREAD

**Issue by baoxin1100** [xxradon/ONNXToCaffe#17]
Hi, thank for your excellent work,
but there are some err when convert model, i think it's because I use torch.split, can you give me some advice about this err. 

err log like below:
```
GlobalAveragePool_46 GlobalAveragePool
Conv_47 Conv
Shape_48 Shape
Traceback (most recent call last):
  File "convertCaffe.py", line 122, in <module>
    convertToCaffe(graph, opset_version, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 64, in convertToCaffe
    err.unsupported_op(node)
  File "/home/liaobaoxin.lbx/ONNXToCaffe/onnx2caffe/_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
TypeError: ONNX node of type Shape is not supported.
```
look forward to your reply

**Comment by baoxin1100** [comment]
oh, I found out that it is not the problem of torch.split
