### ISSUE TITLE
TypeError: ONNX node of type Pad is not supported

### ISSUE THREAD

**Issue by imistyrain** [xxradon/ONNXToCaffe#4]
when run python test.py got this error
with python3.6 
pytorch==1.4
onnx==1.8.0

full log:
```
export broadcast_mul onnx model ...
graph(%input.1 : Float(1, 3, 4, 4),
      %conv1.0.weight : Float(128, 3, 3, 3),
      %conv1.0.bias : Float(128),
      %conv1.1.weight : Float(128),
      %conv1.1.bias : Float(128),
      %conv1.1.running_mean : Float(128),
      %conv1.1.running_var : Float(128),
      %conv1.1.num_batches_tracked : Long()):
  %8 : Float(1, 128, 4, 4) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%input.1, %conv1.0.weight, %conv1.0.bias) # D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py:342:0
  %9 : Float(1, 128, 4, 4) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%8, %conv1.1.weight, %conv1.1.bias, %conv1.1.running_mean, %conv1.1.running_var) # D:\Anaconda3\lib\site-packages\torch\nn\functional.py:1670:0
  %10 : Float(1, 128, 4, 4) = onnx::Relu(%9) # D:\Anaconda3\lib\site-packages\torch\nn\functional.py:912:0
  %11 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%10)
  %12 : Float(1, 128, 1, 1) = onnx::AveragePool[kernel_shape=[4, 4], pads=[0, 0, 0, 0], strides=[4, 4]](%11) # D:\Anaconda3\lib\site-packages\torch\nn\modules\pooling.py:554:0
  %13 : Float(1, 128, 4, 4) = onnx::Mul(%10, %12) # f:\OpenGit\ONNXToCaffe\model_generator\broadcast_mul.py:23:0
  return (%13)

converting broadcast_mul to caffe ...
8 Conv
9 BatchNormalization
10 Relu
11 Pad
  File "ONNXToCaffe\test.py", line 44, in <module>
    caffe_model = convertToCaffe(graph[0], graph[1], prototxt_path, caffemodel_path)
  File "ONNXToCaffe\convertCaffe.py", line 64, in convertToCaffe
    err.unsupported_op(node)
  File "ONNXToCaffe\onnx2caffe\_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
TypeError: ONNX node of type Pad is not supported.
```

**Comment by xxradon** [comment]
Pad is is not supportted in caffe,maybe you can implement Pad operation in caffe.

**Comment by chenkangyang** [comment]
@imistyrain 
#10 #9 #8 
高版本onnx，算子更细，使用 onnx-simplifier 先简化结构，融合一些算子使得caffe能够识别
```
pip install onnx-simplifier
python -m onnxsim $onnx_model $simple_onnx_model
```
```
50. Add_49
51. Relu_50
52. Pad_51
53. AveragePool_52
54. Shape_53
55. Constant_54
56. Gather_55
57. Unsqueeze_56
58. Concat_57
59. Reshape_58
60. Gemm_59
```
简化后
```
50. Add_49
51. Relu_50
52. AveragePool_52
53. Reshape_58
54. Gemm_59
```
再执行onnx2caffe转换

**Comment by Answergeng** [comment]
> @imistyrain #10 #9 #8 高版本onnx，算子更细，使用 onnx-simplifier 先简化结构，融合一些算子使得caffe能够识别
> 
> ```
> pip install onnx-simplifier
> python -m onnxsim $onnx_model $simple_onnx_model
> ```
> 
> ```
> 50. Add_49
> 51. Relu_50
> 52. Pad_51
> 53. AveragePool_52
> 54. Shape_53
> 55. Constant_54
> 56. Gather_55
> 57. Unsqueeze_56
> 58. Concat_57
> 59. Reshape_58
> 60. Gemm_59
> ```
> 
> 简化后
> 
> ```
> 50. Add_49
> 51. Relu_50
> 52. AveragePool_52
> 53. Reshape_58
> 54. Gemm_59
> ```
> 
> 再执行onnx2caffe转换

老哥 简化后报这个错有遇到过吗？
`Traceback (most recent call last):
  File "convertCaffe.py", line 108, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 52, in convertToCaffe
    err.unsupported_op(node)
  File "/home/cmnit/algorithm/onnx2caffe/onnx2caffe/_error_utils.py", line 35, in unsupported_op
    raise TypeError(
TypeError: ONNX node of type GlobalAveragePool is not supported.
`
看了简化结果对比好像也没处理GlobalAveragePool 算子
